# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/focal64"

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt install gcc make perl
    apt-get install -y ubuntu-desktop-minimal
    echo 'try startx :)'
    apt-get install -y ubuntu-desktop
    echo 'https://www.youtube.com/watch?v=hUqMUhgytyc'


    apt install mysql-server

    add-apt-repository ppa:iconnor/zoneminder-1.36

    apt install -yq zoneminder

    systemctl enable zoneminder.service

    systemctl start zoneminder.service

    ps ax | grep zm

    a2enconf zoneminder
    a2enmod rewrite

    ls -l /etc/apache2/conf-enabled/ | grep zoneminder

    ls -l /etc/apache2/mods-enabled/

    systemctl reload apache2

    curl http://localhost/zm/

    # now, zoneminder should be installed...

    # below this is how to find video devices

    apt install v4l2-ctl
    v4l2-ctl --list-devices

    # This is necessary to give permissions to zoneminder (apache) to read /dev/video* devices
    # https://forums.zoneminder.com/viewtopic.php?t=23361
    adduser www-data video
    usermod -a -G video www-data
    sudo a2enmod cgi
    systemctl reload apache2
    # then reboot
  SHELL
end
