# -*- mode: ruby -*-
# vi: set ft=ruby :

VM_NAME = 'Ubuntu 18.04 Development'
VM_RAM_MB='3000'

Vagrant.configure("2") do |config|

  config.vm.box = "generic/ubuntu1804"
  config.vm.define VM_NAME

  # VirtualBox specific settings
  config.vm.provider "virtualbox" do |vb|
    # Show the VirtualBox GUI when booting the machine
    vb.gui = true

    # Customize the amount of memory on the VM:
    vb.memory = VM_RAM_MB

  end

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt install -y apt-transport-https
    apt install -y software-properties-common wget
    apt install -y tasksel
    apt install -y ubuntu-desktop
    apt install -y docker docker-compose
    apt install -y snap
    apt install -y virtualbox-guest-additions-iso
    sudo snap install --classic code
  SHELL
end
