# -*- mode: ruby -*-
# vi: set ft=ruby :

VM_NAME = 'Ubuntu 18.04 Development'
VM_RAM_MB = '6000'

Vagrant.configure("2") do |config|

  config.vm.box = "generic/ubuntu1804"
  config.vm.define VM_NAME

  # VirtualBox specific settings
  config.vm.provider "virtualbox" do |vb|
    # Show the VirtualBox GUI when booting the machine
    vb.gui = true

    # Customize the amount of memory on the VM:
    vb.memory = VM_RAM_MB

  end

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update

    apt install -y fish
    echo 'vagrant' | chsh vagrant -s /usr/bin/fish

    apt install -y ubuntu-desktop #takes forever

    apt install -y gcc make perl ruby
    gem install mdless
    apt install -y apt-transport-https
    apt install -y software-properties-common wget
    apt install -y tasksel
    apt install -y docker docker-compose
    apt install -y openjdk-11-jdk
    apt install -y snap
    apt install -y virtualbox-guest-additions-iso
    
    apt install -y vagrant packer
    sudo snap install --classic code

    sudo snap install --classic kubectl
    sudo snap install --classic helm

    # minikube stuff
    sudo apt install conntrack
    curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    sudo install minikube-linux-amd64 /usr/local/bin/minikube
    # then run `sudo minikube start --driver=none` to start it 
  SHELL

  config.vm.provision "shell", inline: <<-SHELL
    echo "Done. Take a snapshot!"
    echo "Run: 
    vagrant snapshot save 'after vagrant'"
  SHELL
end
