# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "henryfbp/raspberry-pi-desktop"
  config.vm.box_version = "3"

  config.ssh.username = "pi"
  config.ssh.password = "raspberry"

  config.vm.provision "shell", inline: <<-SHELL
    echo "check dis: https://trustfoundry.net/honeypi-easy-honeypot-raspberry-pi/"
    echo "nothin to do...vanilla rpi :p"
  SHELL
end
