# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "henryfbp/raspberry-pi-desktop"
  config.vm.box_version = "2021-01-11-raspios-buster-i386"

  config.ssh.username = "pi"
  config.ssh.password = "raspberry"

  # Directory that the setup script uses...
  config.vm.synced_folder "./opac-config-dir/", "/data/opac-config-dir/"

  config.vm.provision "shell", path: "./setup-script.sh"

end
