# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "kalilinux/rolling"
#  config.vm.box = "kalilinux/rolling-light"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 9392, host: 9392, host_ip: "127.0.0.1" # openvas

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #

  config.ssh.insert_key = false # Fix for NTFS drives
  config.disksize.size = '150GB'

  # VirtualBox specific settings
  config.vm.provider "virtualbox" do |vb|
    # Show the VirtualBox GUI when booting the machine
    vb.gui = true

    # Customize the amount of memory on the VM:
    vb.memory = "8192"
  end

  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.

  # copy add-apt-repository
  config.vm.provision "file", source:"scripts/add-apt-repository.sh", destination: "/tmp/add-apt-repository"

  # Copy useful scripts to desktop
  config.vm.provision "file",
                      source:"scripts/desktop-scripts/tor-transparent-proxy-start.sh",
                      destination: "/home/vagrant/Desktop/"

  config.vm.provision "file",
                       source:"scripts/desktop-scripts/tor-transparent-proxy-stop.sh",
                       destination: "/home/vagrant/Desktop/"

  # make add-apt-repository executable
  config.vm.provision "shell", run: "always", inline: <<-SHELL
    sudo mv /tmp/add-apt-repository /usr/sbin/add-apt-repository

    chmod +x /usr/sbin/add-apt-repository
  SHELL

  # start timer
  config.vm.provision "shell", run: "always", inline: <<-SHELL
  
    echo `date` > ~/start_vagrant_config  

  SHELL

  # resize main partition to max size
  config.vm.provision "shell", inline: <<-SHELL
  
    echo "Resizing partition to fill the entire filesystem..."

    # exit 1 # debug stop

    # size of new swap, in GB
    NEW_SWAP_SIZE=6 #TODO The real swap size is larger for some reason than it should be. Fix this.

    # Check to see if we've already grown the main partition
    if [ -f /etc/vagrant_already_grown_main_partition ]; then
      echo "/etc/vagrant_already_grown_main_partition exists!"
      echo "We are not going to partition. We have already."
      exit 0
    fi

    # turn off swap
    swapoff /dev/sda5

    (
    echo d # delete part
    echo 2 # extended part 2 which had swap in it
    echo p # print part table before writing
    echo w # write part table
    ) | sudo fdisk /dev/sda
    
    # show partitions
    lsblk

    # Size of entire disk
    SDA_SIZE_GB=$(lsblk /dev/sda | grep "sda " | tr -s ' ' | cut -d ' ' -f 4)
    echo "Disk size is ${SDA_SIZE_GB}."

    # Size of the main partition, minus 6GB for swap.
    SDA_MAIN_PART_SIZE=$(expr ${SDA_SIZE_GB//G} - $NEW_SWAP_SIZE)"G"
    echo "Main partition should be ${SDA_MAIN_PART_SIZE}."

    # Resize /dev/sda1
    (
    echo resizepart # resize a partition
    echo 1  # resize sda1
    echo Yes
    echo ${SDA_MAIN_PART_SIZE} # leave some space for swap
    echo q  # quit
    ) | sudo parted ---pretend-input-tty /dev/sda

    # make partition take up the entire space
    sudo resize2fs /dev/sda1
    
    # show partitions
    lsblk

    (
    echo n  # create new partition
    echo p  # primary partition
    echo 2  # 2nd partition number
    echo    # default first sector (~96GB)
    echo    # default last sector (~100GB or end of disk)

    echo t  # change partition type
    echo 2  # partition 2 is...
    echo 82 # linux swap/solaris
    echo w  # write changes
    ) | sudo fdisk /dev/sda

    # show partitions
    lsblk

    # format swap partition
    sudo mkswap /dev/sda2
    
    # enable swap
    sudo swapon /dev/sda2
  
    # append mount command to /etc/fstab
    echo "# AUTOMATICALLY GENERATED line by kali-vagrant partition resizing script" >> /etc/fstab
    echo "/dev/sda2             swap            swap            default          0   0" >> /etc/fstab
  
    # This will error if we've fucked up /etc/fstab
    sudo mount -a

    # record the fact that we've grown the main partition and DO NOT do it again
    sudo touch /etc/vagrant_already_grown_main_partition

  SHELL

  # useful tools
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    # apt-get upgrade -y # takes too long...

    apt-get install -y htop iftop cpu-checker gedit transmission
    apt-get install -y snapd
    apt-get install -y libreoffice-writer
    sudo systemctl enable snapd.service
    sudo systemctl start snapd.service

    sudo systemctl enable apparmor # Required for `snap run` to work
    sudo systemctl start apparmor # This will stop SSH AFAIK

    snap install discord
    snap install wickrme

    # enpass
    echo "deb https://apt.enpass.io/ stable main" > /etc/apt/sources.list.d/enpass.list
    wget -O - https://apt.enpass.io/keys/enpass-linux.key | apt-key add -
    apt-get update
    apt-get install -y enpass

  SHELL

  # KVM for android studio
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt install -y qemu-kvm libvirt0 virt-manager bridge-utils
  SHELL

  # virtualbox extensions
  config.vm.provision "shell", inline: <<-SHELL
    apt-get install -y build-essential dkms linux-headers-$(uname -r)
    apt-get install -y virtualbox-dkms virtualbox-guest-additions-iso virtualbox-guest-x11

    echo "REBOOT for a larger screen and other virtualbox-guest-additions goodies."

  SHELL

  # kalitorify, a systemwide tor proxy service.
  config.vm.provision "shell", inline: <<-SHELL

  apt-get install -y tor torbrowser-launcher

  if [ ! which kalitorify &> /dev/null ]; then

    pushd /home/vagrant/Desktop/
    git clone https://github.com/brainfucksec/kalitorify.git
    pushd kalitorify

    make install
    chown -R vagrant:vagrant /home/vagrant/Desktop/kalitorify

    echo "Kaltorify installed. Reboot and run 'kalitorify' to get started."

    popd

    rm -rf kalitorify

    popd


  fi

  SHELL

  # Android studio
  config.vm.provision "shell", inline: <<-SHELL

    sudo snap install android-studio --classic

  SHELL

  # stop timer
  config.vm.provision "shell", run: "always", inline: <<-SHELL
  
    echo `date` > ~/stop_vagrant_config  

    echo "Start time:"
    cat ~/start_vagrant_config

    echo "Stop time:"
    cat ~/stop_vagrant_config

  SHELL

  # set password to something more secure
  config.vm.provision "shell", inline: <<-SHELL
  
  exit 0 # Disabled for people who can't paste

  if [ -f /home/vagrant/my_password_is_random ]; then
    echo "Already changed default password."
  fi

  newpassword=`openssl rand -base64 32`
  
  echo "vagrant:$newpassword" | chpasswd

  echo "The new password of the user 'vagrant' is now '$newpassword' -- write it down."
  
  newpassword="im gone now :)"

  touch /home/vagrant/my_password_is_random

  SHELL

end
