# -*- mode: ruby -*-
# vi: set ft=ruby :

# stolen from https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-gitlab-on-ubuntu-18-04

VM_NAME = 'Ubuntu Bionic 18.04 GitLab'
VM_IP = '192.168.33.70' #visit http://192.168.33.70/users/sign_in to log in
VM_RAM_MB = '2000'

Vagrant.configure("2") do |config|

  config.vm.box = "generic/ubuntu1804"

  config.vm.define VM_NAME
  config.vm.network "private_network", ip: VM_IP # XXX Disable this line if the machine fails to provision on Windows

  # disable default shared folder
  config.vm.synced_folder './', '/vagrant', disabled: true
  config.vm.synced_folder 'shared', '/vagrant'


  # VirtualBox specific settings
  config.vm.provider "virtualbox" do |vb|

    # Customize the amount of memory on the VM:
    vb.memory = VM_RAM_MB

  end

  config.vm.provision "shell", inline: <<-BODADO
    #!/bin/env bash
    sudo apt update

    apt-get install -y fish # test apt
    # echo "y\n" | chsh -s /bin/fish vagrant

    sudo apt install ca-certificates curl openssh-server postfix

    pushd /tmp
    curl -LO https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh
    less /tmp/script.deb.sh
    sudo bash /tmp/script.deb.sh
    popd

    sudo apt install gitlab-ce

    # sudo ufw enable
    # sudo ufw allow http
    # sudo ufw allow https
    # sudo ufw allow OpenSSH

    sudo gitlab-ctl reconfigure
    sudo gitlab-ctl status
    BODADO

end
