# -*- mode: ruby -*-
# vi: set ft=ruby :

# stolen from https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-gitlab-on-ubuntu-18-04

VM_NAME = 'Ubuntu Bionic 18.04 GitLab'
VM_IP = '192.168.33.70' #visit http://192.168.33.70/users/sign_in to log in
VM_RAM_MB = '2000'

Vagrant.configure("2") do |config|

  config.vm.box = "generic/ubuntu1804"

  config.vm.define VM_NAME
  config.vm.network "private_network", ip: VM_IP # XXX Disable this line if the machine fails to provision on Windows

  # disable default shared folder
  config.vm.synced_folder './', '/vagrant', disabled: true
  config.vm.synced_folder 'shared', '/vagrant'


  # VirtualBox specific settings
  config.vm.provider "virtualbox" do |vb|

    # Customize the amount of memory on the VM:
    vb.memory = VM_RAM_MB

  end

  config.vm.provision "shell",
  env: {:URL => 'http://'+VM_IP+"/users/sign_in"},
  inline: <<-BODADO
    #!/bin/env bash

    command_exists () {
      type "$1" &> /dev/null ;
    }
  
    sudo apt update

    apt-get install -y fish # test apt

    sudo apt install ca-certificates curl openssh-server postfix

    pushd /tmp
    curl -LO https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh
    less /tmp/script.deb.sh
    sudo bash /tmp/script.deb.sh
    popd

    if command_exists gitlab-ctl ; then
      echo "[i] gitlab-ce not installed, due to gitlab-ctl not existing, installing..."
      sudo apt install gitlab-ce
      sudo gitlab-ctl reconfigure
    else
      echo "[/] gitlab-ce already installed due to gitlab-ctl existing."
    fi

    sudo ufw enable
    sudo ufw allow http
    sudo ufw allow https
    sudo ufw allow OpenSSH

    sudo gitlab-ctl status

    echo "Done, visit $URL to log in."
    echo "Note you will need to manually approve new users since this is a vanilla self hosted GitLab instance."
    echo "Try running 'vagrant ssh' and 'sudo gitlab-ctl'."

    BODADO

end
