Vagrant.configure("2") do |config|
 
    # use 24.04 as it is the latest LTS version
    config.vm.box = "ubuntu/focal64"
    
    # disable shared folders
    config.vm.synced_folder ".", "/vagrant", disabled: true

    # name the VM
    config.vm.hostname = "minecraft-atm-9-to-the-sky"

    config.vm.network "private_network", type: "dhcp"
  
    # forward the port 25565 to the host machine
    config.vm.network "forwarded_port", guest: 25565, host: 25565

    config.vm.provider "virtualbox" do |vb|
      # 8gb ram as this is a chonker of a modpack
      vb.memory = "8192"
      vb.cpus = 4
      # name the VM
      vb.name = "minecraft-atm-9-to-the-sky"
    end
  
    config.vm.provision "ansible" do |ansible|
      ansible.playbook = "minecraft_atm_9_to_the_sky.yaml"
      ansible.verbose = "v"
    end
  end
  