Vagrant.configure("2") do |config|

    config.vm.box = "ubuntu/focal64"
    
    # disable default shared folder
    config.vm.synced_folder './', '/vagrant', disabled: true

    config.vm.provision "shell", inline: <<-SHELL        
        echo "hello :)"

        apt update
        apt install -qy ubuntu-desktop-minimal

        apt install -qy gitk
        
        echo "run startx :)"

        # if ! command -v jetbrains-toolbox &> /dev/null
        # then
        #     echo "jetbrains-toolbox could not be found, downloading"
        #     sudo -H -u vagrant bash -c 'todo, this is broken'
        # else
        #     echo "jetbrains toolbox already installed." 
        # fi

        apt install -y alsa pulseaudio

        cat /proc/cpuinfo | grep avx
        # if grep didn't find "AVX"
        if [ $? -ne 0 ]; then
            cat /proc/cpuinfo
            echo "WARNING: You need 'avx' CPU feature! Things may not work!"
            sleep 10
            # exit $?
        fi

        sudo -H -u vagrant bash -c 'mkdir -p ~/Git'
            
        pushd /home/vagrant/Git
            sudo -H -u vagrant bash -c 'git clone https://github.com/MycroftAI/mycroft-core.git'
            echo "Done cloning Mycroft, go run ./dev_setup.sh -fm"
        popd

        if [ -d /opt/mycroft/skills ]; then
            pushd /opt/mycroft/skills
                sudo -H -u vagrant bash -c 'git clone https://github.com/HenryFBP/mycroft-minecroft-text-game'
            popd
        else
            echo "WARNING: /opt/mycroft/skills does not exist, go run the setup for mycroft then run vagrant provision again."
            sleep 10
        fi

    SHELL
end