# -*- mode: ruby -*-
# vi: set ft=ruby :

VM_NAME = 'Ubuntu Bionic 18.04 Jenkins'
VM_IP = '192.168.33.22'
VM_RAM_MB = '2000'

Vagrant.configure("2") do |config|

  config.vm.box = "hashicorp/bionic64"

  config.vm.define VM_NAME
  config.vm.network "private_network", ip: VM_IP

  # disable default shared folder
  config.vm.synced_folder './', '/vagrant', disabled: true
  config.vm.synced_folder 'shared', '/vagrant'


  # VirtualBox specific settings
  config.vm.provider "virtualbox" do |vb|

    # Customize the amount of memory on the VM:
    vb.memory = VM_RAM_MB

  end

  config.vm.provision "shell", env: {:IP => VM_IP}, inline: <<-SHELL

    #exit 0 #debug    

    wget -q -O - http://pkg.jenkins-ci.org/debian/jenkins-ci.org.key | sudo apt-key add -
    sudo sh -c 'echo deb http://pkg.jenkins-ci.org/debian binary/ > /etc/apt/sources.list.d/jenkins.list'
    sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys FCEF32E745F2C3D5

    apt update

    apt-get install -y openjdk-8-jre
    apt-get install -y jenkins
    systemctl start jenkins

    curl 127.0.0.1:8080

    echo "Jenkins is installed! Log in at ${IP}:8080 and follow the instructions."

    echo "Run 'vagrant ssh' if you need to read files from the VM."

    echo "After that, install the 'Build Pipeline' plugin and get some Git repos with Jenkinsfiles!"

  SHELL
end
