# -*- mode: ruby -*-
# vi: set ft=ruby :

VM_NAME = 'Ubuntu Bionic 18.04 Jenkins'
VM_IP = '192.168.33.22'
VM_RAM_MB = '2000'

Vagrant.configure("2") do |config|

  config.vm.box = "hashicorp/bionic64"

  config.vm.define VM_NAME
  config.vm.network "private_network", ip: VM_IP

  # disable default shared folder
  config.vm.synced_folder './', '/vagrant', disabled: true
  config.vm.synced_folder 'shared', '/vagrant'


  # VirtualBox specific settings
  config.vm.provider "virtualbox" do |vb|

    # Customize the amount of memory on the VM:
    vb.memory = VM_RAM_MB

  end

  config.vm.provision "shell", inline: <<-SHELL

    #exit 0 #debug    

    wget -q -O - http://pkg.jenkins-ci.org/debian/jenkins-ci.org.key | sudo apt-key add -
    sudo sh -c 'echo deb http://pkg.jenkins-ci.org/debian binary/ > /etc/apt/sources.list.d/jenkins.list'
    sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys FCEF32E745F2C3D5

    apt update

    apt-get install -y openjdk-8-jdk
    apt-get install -y maven
    apt-get install -y jenkins
    systemctl enable jenkins
    systemctl start jenkins

    if [ ! -f jenkins-cli.jar ]; then
      wget 127.0.0.1:8080/jnlpJars/jenkins-cli.jar
    fi

    java -jar ./jenkins-cli.jar -s "http://127.0.0.1:8080" \
      -auth admin:"$(sudo cat /var/lib/jenkins/secrets/initialAdminPassword)" \
      install-plugin \
      "cloudbees-folder" "antisamy-markup-formatter" "build-timeout" "credentials-binding" "rebuild" "ssh-agent" \
      "timestamper" "ws-cleanup" "ant" "gradle" "nodejs" "workflow-aggregator" "github-branch-source" \
      "pipeline-github-lib" "pipeline-stage-view" "bitbucket" "git" "cvs" "github" "subversion" "ssh-slaves" \
      "matrix-auth" "pam-auth" "ldap" "email-ext" "mailer" "ssh" "publish-over-ssh" "locale" "dependencyanalyzer" \
      "m2release" "maven-info" "maven-plugin" "pipeline-maven" "plot" "violations" "warnings"

  SHELL


  config.vm.provision "shell", run: "always", env: {:IP => VM_IP}, inline: <<-SHELL
    curl 127.0.0.1:8080

    echo "Jenkins is installed! Log in at ${IP}:8080 and follow the instructions."

    echo "Run 'vagrant ssh' if you need to read files from the VM."

    echo "The initial Jenkins admin password is in '/var/lib/jenkins/secrets/initialAdminPassword'."

    echo "After that, get some Git repos with Jenkinsfiles or other repos!"

    echo "A load of extra plugins have been installed."

  SHELL
end
