# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  config.vm.box = "lorenyx/parrotsec"
  config.vm.box_version = "0.0.1"

  config.ssh.username = 'vagrant'
  config.ssh.password = 'vagrant'

  config.vm.provision "shell", path: "./setup.sh"
end
