# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  config.vm.box = "lorenyx/parrotsec"
  config.vm.box_version = "0.0.1"
  
  config.vm.provider 'virtualbox' do |v|
    v.name = "ParrotOS"

    v.gui = true

    v.memory = 6000
    v.cpus = 4

    v.customize ['modifyvm', :id, '--vram', '256']
  end

  config.ssh.username = 'vagrant'
  config.ssh.password = 'vagrant'

  config.vm.provision "shell", path: "./setup.sh"
end
