{ +block{For any non-library material search, please use the public computers.} } #Block all URLs by default

/ # This blocks all URLS by default.

{ -block }

oakbluffslibrary.org
*.oakbluffslibrary.org

clamsnet.org
*.clamsnet.org

commonwealthcatalog.org
*.commonwealthcatalog.org

overdrive.com
*.overdrive.com

ebscohost.com
*.ebscohost.com

galepages.com
*.galepages.com

mblc.state.ma.us
*.mblc.state.ma.us

maps.google.com
docs.google.com
