# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

VM_NAME = 'Windows-Microsoft-Office'
VM_IP = '192.168.33.12'

Vagrant.configure("2") do |config|

  config.vm.box = "gusztavvargadr/windows-10"

  config.vm.synced_folder './', '/sharedfolder'
  config.vm.define VM_NAME

  config.vm.network "private_network", ip: VM_IP


  config.vm.provider 'virtualbox' do |v|
    v.name = VM_NAME

    v.gui = true

    v.memory = 2000
    v.cpus = 2

    v.customize ['modifyvm', :id, '--vram', '256']

#    v.customize ["storageattach", :id,
#                 "--storagectl", "IDE", #README May need to change to "IDE" or "IDE Controller!"
#                 "--port", "0", "--device", "1",
#                 "--type", "dvddrive",
#                 "--medium", "emptydrive"]

  end

  config.vm.provision "shell", privileged: "true", powershell_elevated_interactive: "true",
                      path: "../scripts/install-choco-and-cool-tools.ps1"
 
 config.vm.provision "shell", privileged: "true", powershell_elevated_interactive: "true",
                      path: "../scripts/clone-kms-activator.ps1"

  config.vm.provision "shell", privileged: "true", powershell_elevated_interactive: "true", run: "always",
                      path: "../scripts/download-office-365.ps1"

  #asp.net, needed for some tools
  config.vm.provision "shell", inline: <<-SHELL
    choco install dotnet3.5
    choco install dotnet4.7.2
  SHELL


end
